

instance NONE_117_NERGAL_EXIT(C_Info)
{
	npc = none_117_nergal;
	nr = 999;
	condition = none_117_nergal_exit_condition;
	information = none_117_nergal_exit_info;
	permanent = TRUE;
	description = Dialog_Ende;
};


func int none_117_nergal_exit_condition()
{
	return TRUE;
};

func void none_117_nergal_exit_info()
{
	AI_StopProcessInfos(self);
};


instance NONE_117_NERGAL_HALLO(C_Info)
{
	npc = none_117_nergal;
	condition = none_117_nergal_hallo_condition;
	information = none_117_nergal_hallo_info;
	permanent = FALSE;
	important = TRUE;
};


func int none_117_nergal_hallo_condition()
{
	if(XARDASRITUALFAIL == TRUE)
	{
		return TRUE;
	};
};

func void none_117_nergal_hallo_info()
{
	self.name[ 0 ] = " Soul Nergala " ;
	B_GivePlayerXP(100);
	//Wld_PlayEffect("DEMENTOR_FX",hero,hero,0,0,0,FALSE);
	Wld_PlayEffect("spellFX_Fear",self,self,0,0,0,FALSE);
	Snd_Play("DEM_Warn");
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_01 " );	// (dead voice) MORTAL... So you're the one I have to thank.
	AI_Output(other,self,"NONE_117_Nergal_Hallo_01_02");	//За что?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_03 " );	// For saving me the trouble of answering that worthless old mage's questions.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_04 " );	// And I think that as a reward for your service... I'll let you die last!
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_06 " );	// Well, since you're going to kill me, maybe you can answer just one question before that?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_07 " );	// Want to ask a question? Well, try it, ask it.
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_08 " );	// Tell me, where can I find the Necronomicon?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_09 " );	// Necronomicon? So I was called here to find out where I hid this ancient artifact?
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_10 " );	// Does it really matter to you now?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_11 " );	// No, absolutely nothing... The reasons may sometimes be different, but the result will always be the same.
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_12 " );	// Okay, stop talking! Just answer my question.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_13 " );	// And you're cheeky, as I see... But I like it!
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_14 " );	// Good. I will answer your question, since you are unlikely to be able to use my answer.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_15 " );	// I hid this relic where no mortal like you could ever go...
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_17 " );	// Atop the dark tower of Acheron!
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_18 " );	// Tower of Acheron? Where is she?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_19 " );	// I don't remember exactly... (nostalgically) It was so long ago...
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_20 " );	// It turns out that I just need to find this tower, and we can assume that this artifact is already in my hands.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_21 " );	// Not everything is so simple, mortal... My treasure is guarded by an immortal creature of the Darkness, which you are unlikely to be able to defeat.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_22 " );	// I'm sure a lot of people have tried this. But I am also sure that they are all dead now.
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_23 " );	// And what, there is no way to destroy this creature?
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_24 " );	// Why, there is one. But I won't tell you... You don't even have to ask.
	AI_Output(other,self, " NONE_117_Nergal_Hallo_01_25 " );	// Okay, thanks for that.
	AI_Output(self,other, " NONE_117_Nergal_Hallo_01_26 " );	// Nothing. Now get ready to die... Now I will destroy you!
	B_LogEntry( TOPIC_XARDASTASKSFOUR , " Before attacking me, the soul of the necromancer Nergal spoke to me, and kindly agreed to answer a question about the Necronomicon. As it turned out, this artifact is hidden on top of a certain tower of Acheron, and the entrance to it is guarded by an immortal creature generated by Darkness. There is only one way to kill him, which Nergal, of course, did not tell me about. You will have to find the tower yourself and figure out how to deal with this creature. " );
	KNOWWHERENERCONOMICON = TRUE;
	Info_ClearChoices(none_117_nergal_hallo);
	Info_AddChoice(none_117_nergal_hallo, " Well, try it if you can. " ,none_117_nergal_hallo_ex1);
};

func void none_117_nergal_hallo_ex1()
{
	AI_Output(other,self, " NONE_117_Nergal_Hallo_Ex1_01_01 " );	// Well, try it if you can.
	AI_Output(self,other,"NONE_117_Nergal_Hallo_Ex1_01_02");	//Аргххх...(мертвым голосом)
	self.flags = NPC_FLAG_NONE;
	Wld_StopEffect("DEMENTOR_FX");
	AI_StopProcessInfos(self);
	self.aivar[AIV_EnemyOverride] = FALSE ;
};


